from __future__ import annotations

import os
import random
from datetime import datetime, timedelta

from pyspark.sql import DataFrame
from pyspark.sql.functions import col, lit
from pyspark.sql.types import DoubleType, StructField, StructType

from common import (
    RANDOM_SEED,
    WEATHER_RAW_PATH,
    WEATHER_UPDATE_PATH,
    ensure_updates_dir,
    get_spark,
)

NEW_HOURS = 24 * 7


def _load_raw(spark) -> DataFrame:
    if not os.path.exists(WEATHER_RAW_PATH):
        raise FileNotFoundError(f"Missing raw weather file at {WEATHER_RAW_PATH}")
    return (
        spark.read
        .option("header", True)
        .option("inferSchema", True)
        .csv(WEATHER_RAW_PATH)
    )


def _row_to_dict(row):
    return {f: row[f] for f in row.__fields__}


def generate() -> dict:
    ensure_updates_dir()
    spark = get_spark("Week3 Task1 - weather update generator")
    rng = random.Random(RANDOM_SEED)

    raw = _load_raw(spark)
    raw_columns = raw.columns
    raw_count = raw.count()

    max_row = raw.orderBy(
        col("year").desc(),
        col("month").desc(),
        col("day").desc(),
        col("hour").desc(),
    ).limit(1).collect()[0]

    max_ts = datetime(
        int(max_row["year"]),
        int(max_row["month"]),
        int(max_row["day"]),
        int(max_row["hour"]),
    )

    template_rows = (
        raw.orderBy(
            col("year").desc(),
            col("month").desc(),
            col("day").desc(),
            col("hour").desc(),
        )
        .limit(NEW_HOURS)
        .collect()
    )
    templates = [_row_to_dict(r) for r in template_rows]

    def _jitter(value, spread):
        if value is None:
            return None
        try:
            return round(float(value) + rng.uniform(-spread, spread), 2)
        except (TypeError, ValueError):
            return value

    new_rows = []
    for i in range(1, NEW_HOURS + 1):
        ts = max_ts + timedelta(hours=i)
        template = templates[(i - 1) % len(templates)]

        row = dict(template)
        row["year"] = ts.year
        row["month"] = ts.month
        row["day"] = ts.day
        row["hour"] = ts.hour

        if "temp" in row:
            row["temp"] = _jitter(row.get("temp"), 1.5)
        if "prcp" in row:
            base = row.get("prcp") or 0.0
            row["prcp"] = round(max(0.0, float(base) + rng.uniform(-0.2, 0.5)), 2)
        if "wspd" in row:
            row["wspd"] = _jitter(row.get("wspd"), 2.0)
        if "pres" in row:
            row["pres"] = _jitter(row.get("pres"), 1.0)
        if "wdir" in row:
            wd = row.get("wdir")
            if wd is not None:
                row["wdir"] = int((int(wd) + rng.randint(-20, 20)) % 360)

        row["humidity"] = round(rng.uniform(20.0, 100.0), 1)

        new_rows.append(row)

    output_columns = raw_columns + ["humidity"]
    # Build an explicit schema derived from the raw file's inferred schema.
    # Without this, ``createDataFrame`` fails on columns that happen to be
    # ``None`` in every sampled template row (e.g. ``snwd`` / ``wpgt`` in the
    # weather feed are almost always empty).
    output_schema = StructType(
        list(raw.schema.fields) + [StructField("humidity", DoubleType(), True)]
    )
    update_df = spark.createDataFrame(
        [[r.get(c) for c in output_columns] for r in new_rows],
        schema=output_schema,
    )

    tmp_out = WEATHER_UPDATE_PATH + ".tmp"
    (
        update_df
        .coalesce(1)
        .write.mode("overwrite")
        .option("header", True)
        .csv(tmp_out)
    )
    part = [f for f in os.listdir(tmp_out) if f.endswith(".csv")]
    if len(part) != 1:
        raise RuntimeError(f"Expected one part file, found {part}")
    if os.path.exists(WEATHER_UPDATE_PATH):
        os.remove(WEATHER_UPDATE_PATH)
    os.replace(os.path.join(tmp_out, part[0]), WEATHER_UPDATE_PATH)
    for f in os.listdir(tmp_out):
        os.remove(os.path.join(tmp_out, f))
    os.rmdir(tmp_out)

    manifest = {
        "dataset": "weather",
        "format": "csv",
        "output_path": os.path.relpath(WEATHER_UPDATE_PATH),
        "original_row_count": raw_count,
        "original_max_timestamp": max_ts.isoformat(),
        "new_records": len(new_rows),
        "duplicate_records": 0,
        "schema_changes": [
            {
                "column": "humidity",
                "type": "double",
                "change": "added",
                "value_range": [20.0, 100.0],
                "description": "Relative humidity as a numeric percentage.",
            }
        ],
        "notes": (
            "Generated by perturbing values sampled from the last week of the "
            "original data and shifting timestamps forward by one hour "
            "increments."
        ),
    }

    spark.stop()
    return manifest


if __name__ == "__main__":
    m = generate()
    print("weather update generated:")
    for k, v in m.items():
        print(f"  {k}: {v}")
